/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_dlr_droidcontutorial_DroidconNative */

#ifndef _Included_de_dlr_droidcontutorial_DroidconNative
#define _Included_de_dlr_droidcontutorial_DroidconNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_dlr_droidcontutorial_DroidconNative
 * Method:    calcFibonacci
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_de_dlr_droidcontutorial_DroidconNative_calcFibonacci
  (JNIEnv *, jclass, jint);

/*
 * Class:     de_dlr_droidcontutorial_DroidconNative
 * Method:    getName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_de_dlr_droidcontutorial_DroidconNative_getName
  (JNIEnv *, jclass);

/*
 * Class:     de_dlr_droidcontutorial_DroidconNative
 * Method:    setName
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_de_dlr_droidcontutorial_DroidconNative_setName
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
